spring.application.name=ch08_boot
spring.datasource.url=jdbc:mariadb://localhost:3306/ch8db
spring.datasource.username=root
spring.datasource.password=user-19
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver