spring.application.name=ch8_boot
# MariaDB ?? ??
spring.datasource.url=jdbc:mariadb://localhost:3306/ch8db
spring.datasource.username=root
spring.datasource.password=my1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===== JPA ?? =====
# Entity ???? DB ??? ??? ????
# ??? ????? ??? ?? ??/????.
# ?? ?????? ????, ????? ?? validate ?? none? ?? ????
spring.jpa.hibernate.ddl-auto=update

# JPA? ???? SQL? ??? ????
spring.jpa.show-sql=true

# ???? SQL? ?? ?? ?????.
spring.jpa.properties.hibernate.format_sql=true

# MariaDB? ?? SQL? ???? Hibernate?? ????
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
